org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=false

kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048m

android.useAndroidX=true
android.nonTransitiveRClass=true

# iOS / Kotlin Native
kotlin.native.cacheKind=none
kotlin.mpp.androidSourceSetLayoutVersion=2
